# Generated by Django 5.1.3 on 2024-12-27 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_bookmark_remove_recruitdetail_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_info", models.CharField(blank=True, help_text="배우 소개", max_length=255)),
                ("stature", models.IntegerField()),
                ("weight", models.FloatField()),
                ("specialty", models.CharField(blank=True, max_length=255)),
                ("agency", models.CharField(blank=True, max_length=255)),
                ("sns", models.CharField(blank=True, max_length=255)),
                ("bookmark", models.ManyToManyField(blank=True, to="pages.bookmark")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActorImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        upload_to="Actor_images/",
                        validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png"])],
                        verbose_name="배우 이미지",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pages.actor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActorVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "video",
                    models.FileField(
                        upload_to="Actor_videos/",
                        validators=[django.core.validators.FileExtensionValidator(["mp4", "avi", "mov"])],
                        verbose_name="배우 동영상",
                    ),
                ),
                ("title", models.CharField(blank=True, help_text="동영상 제목", max_length=100)),
                ("description", models.TextField(blank=True, help_text="동영상 설명")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="pages.actor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgeRange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("10대 이하", "10대 이하"),
                            ("10대", "10대"),
                            ("20대", "20대"),
                            ("30대", "30대"),
                            ("40대", "40대"),
                            ("50대", "50대"),
                            ("60대", "60대"),
                            ("60대 이상", "60대 이상"),
                        ],
                        default=1,
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("초등학교", "초등학교"),
                            ("중학교", "중학교"),
                            ("고등학교", "고등학교"),
                            ("대학교", "대학교"),
                            ("기타", "기타"),
                        ],
                        default=1,
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gender", models.CharField(choices=[("남자", "남자"), ("여자", "여자")], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Recruit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=100, verbose_name="TITLE")),
                ("post_at", models.DateField(help_text="공고 등록일")),
                ("closing_at", models.DateField(help_text="공고 마감일")),
                ("progress", models.BooleanField(default=False, help_text="진행상황")),
                ("movie_title", models.CharField(blank=True, max_length=100, verbose_name="TITLE")),
                ("director", models.CharField(max_length=50, verbose_name="감독")),
                ("production", models.CharField(max_length=100, verbose_name="제작사")),
                ("requirements", models.TextField(verbose_name="모집 상세 내용")),
                ("casting_type", models.CharField(max_length=50, verbose_name="모집 유형")),
            ],
            options={
                "verbose_name": "공고",
                "verbose_name_plural": "공고들",
                "db_table": "recruit",
            },
        ),
        migrations.DeleteModel(
            name="Actor_Info_Category",
        ),
        migrations.RemoveField(
            model_name="recruitmain",
            name="polecategory",
        ),
        migrations.RemoveField(
            model_name="recruitdetail",
            name="apply_method",
        ),
        migrations.RemoveField(
            model_name="recruitdetail",
            name="recruitmain",
        ),
        migrations.RemoveField(
            model_name="recruitmain",
            name="actorcategory",
        ),
        migrations.RemoveField(
            model_name="recruitmain",
            name="bookmarks",
        ),
        migrations.RemoveField(
            model_name="recruitmain",
            name="work_category",
        ),
        migrations.RemoveField(
            model_name="application",
            name="age",
        ),
        migrations.RemoveField(
            model_name="category",
            name="Big_name",
        ),
        migrations.RemoveField(
            model_name="category",
            name="Small_name",
        ),
        migrations.AlterField(
            model_name="actorcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("주연", "주연"),
                    ("조연", "조연"),
                    ("단역", "단역"),
                    ("아역", "아역"),
                    ("단원", "단원"),
                    ("엑스트라", "엑스트라"),
                    ("기타", "기타"),
                ],
                default=1,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="howtocategory",
            name="method",
            field=models.CharField(
                choices=[("--", "--"), ("Email", "Email"), ("Phone", "Phone"), ("양식", "양식")],
                default=1,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="age_range",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="pages.agerange", verbose_name="나이"
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="education",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pages.education"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="gender",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="pages.gender", verbose_name="성별"
            ),
        ),
        migrations.AddField(
            model_name="recruit",
            name="apply_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.howtocategory", verbose_name="지원 방법"
            ),
        ),
        migrations.AddField(
            model_name="recruit",
            name="bookmark",
            field=models.ManyToManyField(blank=True, to="pages.bookmark"),
        ),
        migrations.AddField(
            model_name="recruit",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="작품 카테고리",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.category",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="recruit",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="pages.recruit"),
        ),
        migrations.AlterField(
            model_name="recruitimage",
            name="recruit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="pages.recruit",
            ),
        ),
        migrations.DeleteModel(
            name="PoleCategory",
        ),
        migrations.DeleteModel(
            name="RecruitDetail",
        ),
        migrations.AddField(
            model_name="category",
            name="big_name",
            field=models.CharField(
                choices=[
                    ("--", "--"),
                    ("영화", "영화"),
                    ("드라마", "드라마"),
                    ("연극", "연극"),
                    ("CF", "CF"),
                    ("엔터테이먼트", "엔터테이먼트"),
                    ("웹드라마", "웹드라마"),
                    ("뮤지컬", "뮤지컬"),
                    ("기타", "기타"),
                ],
                default=1,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="small_name",
            field=models.CharField(
                choices=[("--", "--"), ("장편", "장편"), ("단편", "단편"), ("CF", "CF"), ("기타", "기타")],
                default=1,
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="RecruitMain",
        ),
    ]
