# Generated by Django 5.1.3 on 2024-12-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="이메일")),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1, verbose_name="성별"
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15, verbose_name="전화번호")),
                ("height", models.FloatField(blank=True, default=0, verbose_name="키")),
                ("weight", models.FloatField(blank=True, default=0, verbose_name="몸무게")),
                ("self_introduced", models.TextField(blank=True, null=True, verbose_name="자기소개")),
                ("portfolio", models.BinaryField(null=True, verbose_name="포트폴리오")),
                ("birthday", models.DateField(null=True, verbose_name="생일")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="custom_user_set", to="auth.group", verbose_name="그룹"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_permissions_set",
                        to="auth.permission",
                        verbose_name="권한",
                    ),
                ),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저들",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="회사 이메일")),
                ("name", models.CharField(max_length=50, verbose_name="회사 이름")),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("phone_number", models.CharField(blank=True, max_length=15, verbose_name="회사 전화번호")),
                ("company_url", models.URLField(blank=True, max_length=50, verbose_name="회사 홈페이지")),
                ("description", models.TextField(blank=True, null=True, verbose_name="회사 설명")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="custom_company_set", to="auth.group", verbose_name="그룹"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_company_permissions_set",
                        to="auth.permission",
                        verbose_name="권한",
                    ),
                ),
            ],
            options={
                "verbose_name": "회사",
                "verbose_name_plural": "회사들",
                "db_table": "company",
            },
        ),
    ]
