# Generated by Django 5.1.3 on 2024-12-11 10:02

import django.utils.timezone
from django.db import migrations, models

import members.validators


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("members", "0002_company_address_user_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="height",
        ),
        migrations.RemoveField(
            model_name="user",
            name="self_introduced",
        ),
        migrations.RemoveField(
            model_name="user",
            name="weight",
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="가입일"),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="설명"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(choices=[("user", "User"), ("company", "Company")], default="user", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, validators=[members.validators.validate_kakao_address], verbose_name="주소"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="생일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="portfolio",
            field=models.FileField(blank=True, null=True, upload_to="portfolios/", verbose_name="포트폴리오"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
