# Generated by Django 5.1.3 on 2024-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_user_options_remove_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_url",
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name="화사 URL"),
        ),
    ]
